version: '3.8'

services:
  game-starter:
    image: virtuals-game-starter
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - API_KEY=
      - OPENAI_API_KEY=
      - botToken=
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - virtuals:/app
    restart: always

volumes:
    virtuals: